import type { CSSProperties } from "react";

/** Co-located styles for the shared Context attachments panel. */
export const s = {
  wrap: { padding: 24, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  filterWrap: { marginLeft: "auto", minWidth: 220 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5, margin: 0 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowAttached: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  reorderCol: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  reorderSpacer: { width: 22 } satisfies CSSProperties,
  meta: { flex: 1, minWidth: 0, display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  name: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  tokens: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  total: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  trustLine: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
    textAlign: "right",
  } satisfies CSSProperties,
  budgetWarn: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  serializesLabel: {
    fontSize: 11,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    margin: "8px 0 6px",
  } satisfies CSSProperties,
  serializesBox: {
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
